In [ ]:
# A nearest neighbor learning algorithm example using TensorFlow library.
# This example is using the MNIST database of handwritten digits
# (http://yann.lecun.com/exdb/mnist/)

# Author: Aymeric Damien
# Project: https://github.com/aymericdamien/TensorFlow-Examples/

In [3]:
import numpy as np
import tensorflow as tf
import read_mnist_data as rmd

# read dataset from disk
DATA_FOLDER = '/home/chengming/TensorFlow-Examples/data/'
TRAIN_IMAGES_SET = 'train-images-idx3-ubyte.gz'
TRAIN_LABELS_SET = 'train-labels-idx1-ubyte.gz'
TEST_IMAGES_SET = 't10k-images-idx3-ubyte.gz'
TEST_LABELS_SET = 't10k-labels-idx1-ubyte.gz'
validation_size = 5000
with open(DATA_FOLDER + TRAIN_IMAGES_SET, 'rb') as f:
    train_images = rmd.extract_images(f)
with open(DATA_FOLDER + TRAIN_LABELS_SET, 'rb') as f:
    train_labels = rmd.extract_labels(f, one_hot = True)
with open(DATA_FOLDER + TEST_IMAGES_SET, 'rb') as f:
    test_images = rmd.extract_images(f)
with open(DATA_FOLDER + TEST_LABELS_SET, 'rb') as f:
    test_labels = rmd.extract_labels(f, one_hot = True)
validation_images = train_images[:validation_size]
validation_labels = train_labels[:validation_size]
train_images = train_images[validation_size:]
train_labels = train_labels[validation_size:]

train_shape = train_images.shape
test_shape = test_images.shape
train_images = train_images.reshape(train_shape[0], train_shape[1]*train_shape[2])
test_images = test_images.reshape(test_shape[0], test_shape[1]*test_shape[2])


print train_images.shape
print train_labels.shape, '\t', train_labels[0][:6], train_labels[0][6:]
print test_images.shape
print test_labels.shape, '\t', test_labels[0]
# Import MINST data
#from tensorflow.examples.tutorials.mnist import input_data
#mnist = input_data.read_data_sets("/home/chengming/TensorFlow-Examples/data/", one_hot=True)

('Extracting', '/home/chengming/TensorFlow-Examples/data/train-images-idx3-ubyte.gz')
('Extracting', '/home/chengming/TensorFlow-Examples/data/train-labels-idx1-ubyte.gz')
('Extracting', '/home/chengming/TensorFlow-Examples/data/t10k-images-idx3-ubyte.gz')
('Extracting', '/home/chengming/TensorFlow-Examples/data/t10k-labels-idx1-ubyte.gz')
(55000, 784)
(55000, 10) 	[ 0.  0.  0.  0.  0.  0.] [ 0.  1.  0.  0.]
(10000, 784)
(10000, 10) 	[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]


In [35]:
xtr = tf.placeholder("float32")#, [None, 784])
xte = tf.placeholder("float32")#, [784])

# Nearest Neighbor calculation using L1 Distance
# Calculate L1 Distance
distance = tf.reduce_sum(tf.abs(tf.add(xtr, tf.neg(xte))), reduction_indices=1)
# Prediction: Get min distance index (Nearest neighbor)
pred = tf.arg_min(distance, 0)
accuracy = 0.

# set GPU memory usage
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)

with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) as sess:
    # loop over test data
    for i in range(100):
        # Get nearest neighbor
        nn_index = sess.run(pred, feed_dict={xtr: train_images, xte: test_images[i,:]})
        # Get nearest neighbor class label and compare it to its true label
        print "Test", i, "Prediction:", nn_index, np.argmax(train_labels[nn_index]), \
            "True Class:", np.argmax(test_labels[i])
        # Calculate accuracy
        if np.argmax(train_labels[nn_index]) == np.argmax(test_labels[i]):
            accuracy += 1./100
    print "Done!"
    print "Accuracy:", accuracy

Test 0 Prediction: 48843 7 True Class: 7
Test 1 Prediction: 23882 2 True Class: 2
Test 2 Prediction: 53741 1 True Class: 1
Test 3 Prediction: 54244 0 True Class: 0
Test 4 Prediction: 47920 4 True Class: 4
Test 5 Prediction: 46900 1 True Class: 1
Test 6 Prediction: 13279 4 True Class: 4
Test 7 Prediction: 36982 9 True Class: 9
Test 8 Prediction: 30628 5 True Class: 5
Test 9 Prediction: 44 9 True Class: 9
Test 10 Prediction: 9092 0 True Class: 0
Test 11 Prediction: 53259 6 True Class: 6
Test 12 Prediction: 50441 9 True Class: 9
Test 13 Prediction: 19676 0 True Class: 0
Test 14 Prediction: 42502 1 True Class: 1
Test 15 Prediction: 13418 5 True Class: 5
Test 16 Prediction: 20215 9 True Class: 9
Test 17 Prediction: 48483 7 True Class: 7
Test 18 Prediction: 24246 3 True Class: 3
Test 19 Prediction: 50328 4 True Class: 4
Test 20 Prediction: 17855 9 True Class: 9
Test 21 Prediction: 13430 6 True Class: 6
Test 22 Prediction: 6226 6 True Class: 6
Test 23 Prediction: 31015 5 True Class: 5
Test 24

In [17]:
# test
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3]])
print a.shape, b.shape
a_in = tf.placeholder("float32", [3,3])
b_in = tf.placeholder("float32", [1,3])
out = tf.add(a_in, tf.neg(b_in))
# set GPU memory usage
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) as sess:
    result = sess.run(out, feed_dict={a_in: a, b_in: b})
print result


(3, 3) (1, 3)
[[ 0.  0.  0.]
 [ 3.  3.  3.]
 [ 6.  6.  6.]]


In [ ]:
### original version

# tf Graph Input
Xtrain = tf.placeholder("float", [None, 784])
Xtest = tf.placeholder("float", [784])
print Xtrain, '\n', Xtest

In [ ]:
### original version

# Nearest Neighbor calculation using L1 Distance
# Calculate L1 Distance
distance = tf.reduce_sum(tf.abs(tf.add(xtr, tf.neg(xte))), reduction_indices=1)
# Prediction: Get min distance index (Nearest neighbor)
pred = tf.arg_min(distance, 0)

accuracy = 0.

# Initializing the variables
init = tf.initialize_all_variables()

In [ ]:
### original version

# Launch the graph
with tf.Session() as sess:
    sess.run(init)

    # loop over test data
    for i in range(len(Xte)):
        # Get nearest neighbor
        nn_index = sess.run(pred, feed_dict={xtr: Xtr, xte: Xte[i, :]})
        # Get nearest neighbor class label and compare it to its true label
        print "Test", i, "Prediction:", np.argmax(Ytr[nn_index]), \
            "True Class:", np.argmax(Yte[i])
        # Calculate accuracy
        if np.argmax(Ytr[nn_index]) == np.argmax(Yte[i]):
            accuracy += 1./len(Xte)
    print "Done!"
    print "Accuracy:", accuracy